CREATE DATABASE IF NOT EXISTS wuki CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wuki;
CREATE TABLE IF NOT EXISTS events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(64) NOT NULL,
  event VARCHAR(64) NOT NULL,
  ts DATETIME(6) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
